[package]
name = "ssdsync"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boolinator = "2.4.0"
clap = { version = "3.1.1", features = ["derive"] }
indicatif = "0.16.2"
nix = "0.23.1"
tokio = { version = "1.15.0", features = ["full"] }